---
title: "GINI and Democratization in LA"
author: "Egor Balalykin"
format: html
editor: visual
---

## INTRODUCTION

Latin America was a region that began to successfully democratize at the end of the 20th century. This fate awaited her despite the extremely high income inequality. The topic of inequality is extremely controversial in terms of its impact on democratization. The topic of this paper will be to identify the impact of income inequality on the level of democratization in Latin American countries. Has democratization been made possible by inequality? Or are there any other factors that contribute to democratization despite the high level of inequality? After statistical analysis, an assessment of the degree of influence of both the main variable under study (inequality) and the effect of control variables will be given.

# LITERATURE REVIEW

The relationship between income inequality and democracy is a subject of extensive academic debate, with scholars expressing different opinions. Ansell and Samuels (2007) assert that increasing inequality can promote democratization by enabling emerging social groups to advocate for institutional changes. Conversely, Burkhart (2007) argues that inequality frequently intensifies political inequalities, which could threaten democratic institutions. In addition, Acemoglu et al (2006) argue that in countries with high income inequality a rich elite will struggle against democratization more intensely, as potential call for redistributive policies under democratic regime will result in substantial economic loss for the former. In Krauss (2014) a third point of view is expressed. He claims that existing methodology and complexity of societies make it impossible to identify the real influence of inequality on democracy. It could be inferred that while some scholars view income inequality as a democratizing force under specific conditions, while others highlight its destabilizing effects or suggest that democratization hinges on broader historical and economic contexts rather than inequality itself. In other words, there is no consensus in academic community on this issue. It seems it would be interesting to analyze what are the relations between income inequality and democracy in Latin American regional context.

The relationship between economic growth and democratization has been a highly popular topic of research among economists and political scientists. Lipset (1959) argues that economic growth is likely to positively affect democratization. In Treisman (2020) it is said that there is a observable connection between economic development and income level on one side and democratization on the other. Heo and Tan (2001) show that based on their analysis of developing countries, it is “likely” that economic growth creates higher levels of democracy, and vice versa. Gerring et al (2005) observe that economic growth creates societal transformations that facilitate democratic reforms, while emphasizing that factors such as historical circumstances can mitigate this effect. Still, some scholars, for example Acemoglu et al (2008), find no direct influence of economic growth per se on democratization, pointing out that many other institutional and societal factor should be controlled. These thoughts lay in the logic of so-called modernization theory which basically argues that the more developed society becomes the more chances it has to democratize. One can claim that although much is said regarding the supposed beneficial impact of economic growth on democracy, a number of regional or country-specific factors may significantly mediate this influence.

Finally, education is a crucial expenditure item of the state budget of any country. The degree of influence of their size is also a matter of debate. A widely-known libertarian economist MiltonFriedman (1962) expressed an opining that educated society are more likely to create stable democratic political engagement. Alemán and Kim (2015) claim that democratization usually occurs with countries with rising education levels. They also note that the democratizing effect is stronger in poor countries. However, there is an alternative point of view. However, an alternative point of view also exists. As claimed by Acemoglu et al (2005), there is quite poor direct relations between more education and higher levels of democracy. They say, by using a lot of cross-county data that other factors influence both education and democracy, while mitigating the direct connection between these two factors.

In conclusion, it can be said that no consensus is establish on the effect of the aforementioned variables on democracy level. There are claims that both with economic growth and education country-specific factors work that influence the end result. Simultaneously, there are competing views on the impact of income inequality on democratization. So, given that Latin American countries have a lot country-specific characteristics, but also common ones (such as former colonies and chronicle high levels of inequality), it would be intriguing analyze the dependence of income inequality on Latin American democracy, while controlling the effect of economic growth and education expenditures.

# RESEARCH DESIGN

In order to examine how income inequality affects the democracy levels in Latin American countries, I will use a regression analysis. To investigate the direct correlation between the GINI index and the degree of democracy according to the Index of Democratization, I will first do a straightforward linear regression. In order to observe how taking economic growth into account modifies the main association, I will then construct a bivariate regression model by using GDP per capita as a control variable. Lastly, in order to develop a more comprehensive model I will incorporate education spending as a proportion of GDP and GDP per capita. I am going to systematically assess how other factors interact with and improve the relationship between income inequality and democracy thanks to my multi-layered methodology.

# DATA SOURCES

**DATA SOURCES**

**Level of Democracy (Dependent Variable):** Index of Democratization is one of the data sources for democracy levels. It has a very wide range of data, so data for countries under consideration is available. Index of Democratization is a reputable democracy metric with an open and well-established methodology and is easily accessible through Quality of Governance website and easy for programming using R language. 0 means that a country is a dictatorship with no political freedom and monopolization of power.

**Income Inequality (Independent Variable):** The GINI index will serve as the measure of income inequality. Data can be extracted from the World Bank database. Its global coverage and methodological consistency make it an appropriate choice for studying regional trends like those in Latin America. It is an appropriate source for cross-country studies in general and Latin America in particular, due to its global coverage.

**GDP per Capita (Control Variable 1):** GDP per capita data can also be accessed at the Quality of Governance website, will be used to account for economic growth per person and its respective (potential) effect on democratization in a multivariate regression.

**Education Expenditure (Control Variable 2):** Education expenditure as a percentage of GDP will be sourced from the World Bank as well and other sources are present in Codebook as well. This variable captures public expenditures on this sector and is particularly relevant for exploring socioeconomic conditions affecting democracy. World Bank databases are easy to access and are widely used in research. Using World Bank and Quality of Governance databases is perfect for answering the research question and hold extremely high level of reliability.
